### ISSUE TITLE
Watermark via opensearch.yml

### ISSUE THREAD

**Issue by ansibleguy** [O-X-L/ansible-role-graylog#1]
It might be cleaner to set the watermarks in the `opensearch.yml`:

```yaml
cluster.routing.allocation.disk.threshold_enabled: true
cluster.routing.allocation.disk.watermark.low: 95%
cluster.routing.allocation.disk.watermark.high: 98%
cluster.routing.allocation.disk.watermark.flood_stage: 99%
```

We could also allow users to provide any other setting.
