### ISSUE TITLE
Wait for OpenSearch to startup

### ISSUE THREAD

**Issue by ansibleguy** [O-X-L/ansible-role-graylog#3]
```
# opensearch
    healthcheck:
        test: ['CMD', 'curl', '-f', 'http://localhost:9200']
        interval: 5s
        timeout: 2s
        retries: 20

# graylog
    depends_on:
      opensearch:
        condition: 'service_healthy'
```
